### ISSUE TITLE
SVG not displaying

### ISSUE THREAD

**Issue by sommesh** [eliot-akira/mna#10]
Hi,
When trying to load the SVG to the img tag I'm getting the below error.
And after fixing the error and try loading that svg in img tag it's displaying empty view, but whereas it's displaying in create react app.

```
<img
alt="logo"
className="logo"
src={"../../assets/images/car.svg"}
/>
```

Terminal error :
```
Building client and server..
Server Failed to compile with 1 errors
error in ./src/assets/images/car.svg

Syntax Error: SyntaxError: unknown: Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.
  2 | 
  3 | function SvgCar(props) {
> 4 |   return <svg xmlns:svg="http://www.w3.org/2000/svg" width={350.66} height={248} viewBox="0 0 1052.3622 744.09448" {...props}><title>{"little red racing car"}</title><defs><filter id="e" colorInterpolationFilters="sRGB"><feGaussianBlur stdDeviation={0.57264819} /></filter><radialGradient id="a" gradientUnits="userSpaceOnUse" cy={-15.034} cx={22.681999} gradientTransform="matrix(1 0 0 2.37143 0 19.952)" r={3.2432001}><stop stopColor="#e7e7e7" offset={0} /><stop stopColor="#565656" offset={1} /></radialGradient><linearGradient id="b" y2={35.870998} gradientUnits="userSpaceOnUse" x2={10.783} gradientTransform="matrix(1.04306 0 0 1.04306 -1.034.... 
```

Following this [link](https://github.com/facebook/create-react-app/issues/7955#issuecomment-552118189) tweaked the SVG code.

Now the SVG is tweaked, and then tried to run but still, the SVG is not showing in the UI.

Just to cross-check I have tried the same in react project (create-react-app) and it seems like SVG image loaded there correctly without even tweaking the SVG.

Please share your comments on displaying the SVG image.

**Comment by eliot-akira** [comment]
For using an SVG element directly in React, it's true that attributes like `xmlns:svg` need to be removed or modified for JSX syntax.

For loading an SVG file, I think the issue is using relative path in the `src` attribute. It should be a URL that points to a file in the `build` directory, as a static asset. Maybe `create-react-app` has a loader that converts it.

You can try placing the SVG file in the `static` folder of the app, like in `static/images`. That can be referenced in the img tag as:

```
<img src="/images/car.svg" />
```
