### ISSUE TITLE
for api custom url for login and baseurl

### ISSUE THREAD

**Issue by saikirubamj** [eliot-akira/mna#2]
Hello @eliot-akira ,

We are exploring mna, so we took template-basic folder as  base project. we installed mna package using npm command . Now we are trying  to use custom base url for api .
The api url code in following path ./node_modules/@mna/api/api.js
line no 107 

  this.axios = _axios.default.create(_objectSpread({
      baseURL:url
    },
or  we need to change /api to some custom url  in the following path ./node_nodules/mna/content-client/state/index.js
line no: 75
=> _api2.default.post('/api', {
    type: 'user',
    action: 'login',
    data
  })

we changed url with respectively custom-url it working fine

But one thing every time we need to changes in node_modules folder, there is any other way apart this .

Kindly provide us any solution for this problem.

Regards.,
**Saikiruba.M.J**

**Comment by eliot-akira** [comment]
Hi @saikirubamj ,

Yes, I see what you mean. The files in `node_modules` folder are not meant to be directly edited, because they get overwritten on npm install/update.

Here's what I typically do to develop modules in parallel with the app itself. I clone a Git repository in the `src` folder.

```sh
cd src
git clone https://github.com/eliot-akira/mna @mna
git checkout -b [name_of_your_new_branch]
```

The last step is not necessary, but it might help to keep things organized, to create a new branch for making customizations.

Then `cd ..` and add that folder in `.gitignore`.

```
/src/@mna
```

In this case, I install it as `@mna`, because the repo contains modules that are published individually under that namespace, like `@mna/api`.

From that point, all `@mna` modules will be loaded from `src` instead of `node_modules`. This works because the builder extends the Node.js module resolution logic to search `src` first - so anything installed there can override ones in `node_modules`. It's useful for developing modules locally.

---

I believe the `@mna/api` module has a way to change the API endpoint's base URL. Ah yes, I see it:

```js
import api from '@mna/api'

api.setDefaultOptions({
  baseURL: '/new-api'
})
```

**Comment by saikirubamj** [comment]
Yeah! Thank you @eliot-akira

**Comment by saikirubamj** [comment]
Hi @eliot-akira 


I have tried as per your comment above  i got a iisues  while npm start

1. I have cloned mna in src directory and install mna package 
2, While starting npm start

![image](https://user-images.githubusercontent.com/48011458/80359217-22994580-889b-11ea-821a-7590ea01fa8f.png)

Kindly provide us any solution for this problem.

**Comment by saikirubamj** [comment]
Hi @eliot-akira 

Incase we tried without install mna .
I have cloned mna in src directory by making some path correct in mna core file

![image](https://user-images.githubusercontent.com/48011458/80360638-4493c780-889d-11ea-826a-3f1d299f52c7.png)

Kindly provide us any solution for this problem.

**Comment by eliot-akira** [comment]
This is due to using a different builder based on `react-scripts`, which do not have the same set of Babel plugins compared to `@mna/builder`. The latter includes [`babel-plugin-react-require`](https://github.com/vslinko/babel-plugin-react-require), which automatically adds `import 'React'` at the top of a file that uses JSX.

It may be possible to use `react-scripts` by adding the necessary plugin(s) to be compatible.
