### ISSUE TITLE
Navigation Issues

### ISSUE THREAD

**Issue by saikirubamj** [eliot-akira/mna#4]
Hi @eliot-akira ,

This is about the navigation sessions issues,

Now I'm going from PAGE A to PAGE B then go to PAGE C
So when I click back arrow from PAGE C it needs to come back to the last page here which is PAGE B.
But for us, it's not working like that. it's staying in PAGE C itself or navigating to empty page url.

We are using 

 import { Redirect } from '@mna/react';
`<Redirect `to="page-url-a"/>

Kindly provide us any solution or suggestion for this issues.

**Comment by eliot-akira** [comment]
I believe using Link will work as expected:

```js
import { Link } from '@mna/react'

<Link to="/page-url-a">Page A<Link>
```

If you need the redirect behavior instead of a link - the fact that it's "navigating to empty page url" sounds like it could be an issue with the Redirect component. Looking at the source, it's a minimal wrapper for React Router's Redirect, so I think it should be working correctly.

Just to confirm: are these pages all within the same site/app? If so, it'd be helpful if you could prepare a minimal example repo that reproduces the issue.

**Comment by saikirubamj** [comment]
Hi @eliot-akira 

Link is not working for redirecting page scenario,but we tried **history.push()** it working fine as per our requirements

Thanks for the needful from your end @eliot-akira
