### ISSUE TITLE
Language Translation

### ISSUE THREAD

**Issue by saikirubamj** [eliot-akira/mna#8]
Hii @eliot-akira
 
We would like to add language translation feature in mna project, we have lot of  references for react project but  it is  quite differ in mna project. Could you please give us some reference for language translation regarding mna

**Comment by eliot-akira** [comment]
The `@mna` library doesn't include any modules or specific integration with translation/internationalization/localization.

If the setup you need requires custom Webpack configurations, or passing data from server to client during rendering, it may be necessary to fork/change parts of the library.

In a way, the `@mna` library is meant to be forked and customized further. It's a collection of modules that I personally found useful, so it's opinionated as to the complete setup. I do maintain and keep it somewhat up-to-date, since a number of production sites/apps use it. But for building your own apps, I'd recommend making the code yours by forking the library and customizing modules how you need.

**Comment by saikirubamj** [comment]
@eliot-akira Okay, thanks for the information.
